name: Android E2E (Maestro local)

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:

jobs:
  e2e-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install dependencies and build APK
        run: |
          npm ci
          cd android && ./gradlew assembleDebug

      - name: Install Maestro CLI
        run: curl -Ls "https://get.maestro.mobile.dev" | bash

      - name: Run emulator and Maestro tests (local)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          arch: x86_64
          target: google_apis
          disable-animations: true
          script: |
            adb wait-for-device
            APK_PATH=android/app/build/outputs/apk/debug/app-debug.apk
            MAESTRO=$HOME/.maestro/bin/maestro
            $MAESTRO test maestro/flows/settings/settings_flow.yaml --app "$APK_PATH" --test-output-dir ./test-results/ci/settings
            $MAESTRO test maestro/flows/dashboard/dashboard_flow.yaml --app "$APK_PATH" --test-output-dir ./test-results/ci/dashboard
            $MAESTRO test maestro/flows/sidemenu/sidemenu_flow.yaml --app "$APK_PATH" --test-output-dir ./test-results/ci/sidemenu
            $MAESTRO test maestro/flows/integration/integration_flow.yaml --app "$APK_PATH" --test-output-dir ./test-results/ci/integration

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: maestro-results-android-local
          path: test-results/ci


